/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalidaRouteImport } from './routes/salida'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntradaRouteImport } from './routes/entrada'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CuposRouteImport } from './routes/cupos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketIdRouteImport } from './routes/ticket.$id'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTarifasRouteImport } from './routes/admin.tarifas'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'

const SalidaRoute = SalidaRouteImport.update({
  id: '/salida',
  path: '/salida',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradaRoute = EntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CuposRoute = CuposRouteImport.update({
  id: '/cupos',
  path: '/cupos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIdRoute = TicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTarifasRoute = AdminTarifasRouteImport.update({
  id: '/admin/tarifas',
  path: '/admin/tarifas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/admin/reportes',
  path: '/admin/reportes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cupos': typeof CuposRoute
  '/dashboard': typeof DashboardRoute
  '/entrada': typeof EntradaRoute
  '/login': typeof LoginRoute
  '/salida': typeof SalidaRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/tarifas': typeof AdminTarifasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cupos': typeof CuposRoute
  '/dashboard': typeof DashboardRoute
  '/entrada': typeof EntradaRoute
  '/login': typeof LoginRoute
  '/salida': typeof SalidaRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/tarifas': typeof AdminTarifasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cupos': typeof CuposRoute
  '/dashboard': typeof DashboardRoute
  '/entrada': typeof EntradaRoute
  '/login': typeof LoginRoute
  '/salida': typeof SalidaRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/tarifas': typeof AdminTarifasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cupos'
    | '/dashboard'
    | '/entrada'
    | '/login'
    | '/salida'
    | '/admin/reportes'
    | '/admin/tarifas'
    | '/admin/usuarios'
    | '/ticket/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cupos'
    | '/dashboard'
    | '/entrada'
    | '/login'
    | '/salida'
    | '/admin/reportes'
    | '/admin/tarifas'
    | '/admin/usuarios'
    | '/ticket/$id'
  id:
    | '__root__'
    | '/'
    | '/cupos'
    | '/dashboard'
    | '/entrada'
    | '/login'
    | '/salida'
    | '/admin/reportes'
    | '/admin/tarifas'
    | '/admin/usuarios'
    | '/ticket/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuposRoute: typeof CuposRoute
  DashboardRoute: typeof DashboardRoute
  EntradaRoute: typeof EntradaRoute
  LoginRoute: typeof LoginRoute
  SalidaRoute: typeof SalidaRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminTarifasRoute: typeof AdminTarifasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  TicketIdRoute: typeof TicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salida': {
      id: '/salida'
      path: '/salida'
      fullPath: '/salida'
      preLoaderRoute: typeof SalidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrada': {
      id: '/entrada'
      path: '/entrada'
      fullPath: '/entrada'
      preLoaderRoute: typeof EntradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cupos': {
      id: '/cupos'
      path: '/cupos'
      fullPath: '/cupos'
      preLoaderRoute: typeof CuposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$id': {
      id: '/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof TicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tarifas': {
      id: '/admin/tarifas'
      path: '/admin/tarifas'
      fullPath: '/admin/tarifas'
      preLoaderRoute: typeof AdminTarifasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/admin/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuposRoute: CuposRoute,
  DashboardRoute: DashboardRoute,
  EntradaRoute: EntradaRoute,
  LoginRoute: LoginRoute,
  SalidaRoute: SalidaRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminTarifasRoute: AdminTarifasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  TicketIdRoute: TicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
